// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package informations

import (
	"context"
	"database/sql"
	"time"
)

const createImageInformation = `-- name: CreateImageInformation :execresult
insert into
  informations (name, created)
values
  (?, ?)
`

type CreateImageInformationParams struct {
	Name    string
	Created time.Time
}

func (q *Queries) CreateImageInformation(ctx context.Context, arg CreateImageInformationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createImageInformation, arg.Name, arg.Created)
}
